apiVersion: v1
kind: Service
metadata:
  name: {{ include "key-server.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "key-server.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.service.port }}
