replicaCount: 1

image:
  repository: rahulinux/key-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: key-server.local
      paths:
        - /

resources:
  limits:
    memory: "256Mi"
  requests:
    cpu: "1"
    memory: "256Mi"

env:
  SERVER_PORT: "8080"
  MAX_SIZE: "1024"
  LOG_LEVEL: "info"

livenessProbe:
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 10

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
